forall(x, implies(is_a(x, PlanetaryBody), has_data(x, diameter)))
forall(x, implies(is_a(x, PlanetaryBody), has_data(x, mass)))
forall(x, implies(is_a(x, PlanetaryBody), has_data(x, rotationPeriod)))
forall(x, implies(is_a(x, PlanetaryBody), has_data(x, satelites)))
forall(x, implies(is_a(x, PlanetaryBody), has_data(x, albedo)))
forall(x, implies(is_a(x, PlanetaryBody), has_data(x, absoluteMagnitude)))
forall(x, implies(is_a(x, Star), is_a(x, PlanetaryBody)))
forall(x, implies(is_a(x, Planet), is_a(x, PlanetaryBody)))
forall(x, implies(is_a(x, DwarfPlanet), is_a(x, PlanetaryBody)))
forall(x, implies(is_a(x, Moon), is_a(x, PlanetaryBody)))
is_a(Sun, Star)
orbits(Mercury, Sun)
is_a(Mercury, Planet)
orbits(Venus, Sun)
is_a(Venus, Planet)
orbits(Earth, Sun)
orbits(Moon, Earth)
is_a(Earth, Planet)
orbits(Mars, Sun)
orbits(Phobos, Mars)
orbits(Deimos, Mars)
is_a(Mars, Planet)
is_a(Phobos, Moon)
is_a(Deimos, Moon)
orbits(Jupiter, Sun)
orbits(Io, Jupiter)
orbits(Europa, Jupiter)
orbits(Ganymede, Jupiter)
orbits(Callisto, Jupiter)
is_a(Jupiter, Planet)
is_a(Io, Moon)
is_a(Europa, Moon)
is_a(Ganymede, Moon)
is_a(Callisto, Moon)
orbits(Saturn, Sun)
orbits(Titan, Saturn)
orbits(Enceladus, Saturn)
is_a(Saturn, Planet)
is_a(Titan, Moon)
is_a(Enceladus, Moon)
orbits(Uranus, Sun)
orbits(Titania, Uranus)
is_a(Uranus, Planet)
is_a(Titania, Moon)
orbits(Neptune, Sun)
orbits(Triton, Neptune)
is_a(Neptune, Planet)
is_a(Tritan, Moon)
orbits(Pluto, Sun)
is_a(Pluto, DwarfPlanet)
